apiVersion: v1
kind: Service
metadata:
  name: weather-apiserver
  namespace: weather-system
  labels:
    app: weather-apiserver
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    app: weather-apiserver
