apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: voting
  annotations:
    kubernetes.io/change-cause: "sécurisation SecurityContext + PSS restricted"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vote
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: vote
          image: mohamed1780/vote
          ports:
            - containerPort: 5000

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          env:
            - name: OPTION_A
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: OPTION_A
            - name: OPTION_B
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: OPTION_B
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: voting-config
                  key: REDIS_PORT
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
            failureThreshold: 3

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
