apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# On hérite de la base — aucune modification nécessaire pour dev
resources:
  - ../../base

# Préfixe les noms des ressources avec "dev-"
namePrefix: dev-

# Ajoute un label d'environnement
commonLabels:
  env: dev

# Déploie dans le namespace dev
namespace: dev
