apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-backend
  template:
    metadata:
      labels:
        app: api-backend
        tier: backend
    spec:
      containers:
        - name: api
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from $(POD_NAME) on node $(NODE_NAME)"
          ports:
            - containerPort: 5678
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "50m"
              memory: "32Mi"
