apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-myapi-config
  labels:
    app: myapi
    managed-by: helm
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
