apiVersion: v1
kind: Secret
metadata:
  name: voting-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "vote-app.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgresUser | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | b64enc }}
