apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: {{ .Values.namespace }}
  labels:
    app: worker
    {{- include "vote-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          envFrom:
            - configMapRef:
                name: voting-config
            - secretRef:
                name: voting-secrets
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
