apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  DB_HOST: "postgres.dev.svc.cluster.local"
  DB_PORT: "5432"
  LOG_LEVEL: "info"
  APP_ENV: "development"
  nginx.conf: |
    server {
      listen 80;
      location / {
        return 200 'ConfigMap nginx OK\n';
        add_header Content-Type text/plain;
      }
      location /health {
        return 200 'OK\n';
        add_header Content-Type text/plain;
      }
    }
